steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/products-app-microservices/image-registry/payments-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/products-app-microservices/image-registry/payments-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
  #
